LineLength:
  Max: 100

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/For:
  Enabled: false # for: For speed!

Style/ModuleFunction:
  Enabled: false

Metrics/MethodLength:
  CountComments: false
  Max: 15
