language: ruby
install: gem install bundler
script: "bundle && bundle exec rake ci"

env:
  global:
    - JRUBY_OPTS="--server -J-Xms1500m -J-Xmx1500m -J-XX:+UseConcMarkSweepGC -J-XX:-UseGCOverheadLimit -J-XX:+CMSClassUnloadingEnabled"

rvm:
  - 2.2.2
  - jruby-9.0.0.0
  - jruby-head
  - rbx-2

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: rbx-2
